# Generated by Django 5.0.6 on 2026-04-15 09:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DollarPrice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dollar_price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='youtubelinks',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('youtubeUrl', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('discount', models.CharField(blank=True, max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('age', models.CharField(choices=[('جديد', 'جديد'), ('مستعمل', 'مستعمل'), ('اوبن بوكس', 'اوبن بوكس')], max_length=20)),
                ('status', models.BooleanField(default=True)),
                ('count', models.IntegerField(default=0)),
                ('url1', models.URLField(blank=True)),
                ('url2', models.URLField(blank=True)),
                ('url3', models.URLField(blank=True)),
                ('url4', models.URLField(blank=True)),
                ('url5', models.URLField(blank=True)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='myapp.producttype')),
            ],
        ),
        migrations.CreateModel(
            name='offer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('oldprice', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.BooleanField(default=True)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='offers/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='offers/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='offers/')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='offers/')),
                ('url1', models.URLField(blank=True)),
                ('url2', models.URLField(blank=True)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='myapp.producttype')),
            ],
        ),
    ]
