# Generated by Django 5.0.6 on 2026-04-15 09:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('discount', models.CharField(blank=True, max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('age', models.CharField(choices=[('جديد', 'جديد'), ('مستعمل', 'مستعمل'), ('اوبن بوكس', 'اوبن بوكس')], max_length=20)),
                ('status', models.BooleanField(default=True)),
                ('count', models.IntegerField(default=0)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('model_number', models.CharField(blank=True, max_length=100)),
                ('compatibility', models.CharField(blank=True, max_length=255)),
                ('url1', models.URLField(blank=True)),
                ('url2', models.URLField(blank=True)),
                ('url3', models.URLField(blank=True)),
                ('url4', models.URLField(blank=True)),
                ('url5', models.URLField(blank=True)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='accessories/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='accessories/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='accessories/')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='accessories/')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='accessories/')),
            ],
        ),
        migrations.CreateModel(
            name='AccessoryType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('discount', models.CharField(blank=True, max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('age', models.CharField(choices=[('جديد', 'جديد'), ('مستعمل', 'مستعمل'), ('اوبن بوكس', 'اوبن بوكس')], max_length=20)),
                ('status', models.BooleanField(default=True)),
                ('count', models.IntegerField(default=0)),
                ('url1', models.URLField(blank=True)),
                ('url2', models.URLField(blank=True)),
                ('url3', models.URLField(blank=True)),
                ('url4', models.URLField(blank=True)),
                ('url5', models.URLField(blank=True)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='computers/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='computers/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='computers/')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='computers/')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='computers/')),
            ],
        ),
        migrations.CreateModel(
            name='ComputerType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('discount', models.CharField(blank=True, max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('age', models.CharField(choices=[('جديد', 'جديد'), ('مستعمل', 'مستعمل'), ('اوبن بوكس', 'اوبن بوكس')], max_length=20)),
                ('status', models.BooleanField(default=True)),
                ('count', models.IntegerField(default=0)),
                ('cpu', models.CharField(blank=True, max_length=255)),
                ('gpu', models.CharField(blank=True, max_length=255)),
                ('ram', models.CharField(blank=True, max_length=100)),
                ('hard', models.CharField(blank=True, max_length=255)),
                ('screen', models.CharField(blank=True, max_length=100)),
                ('color', models.CharField(blank=True, max_length=50)),
                ('os', models.CharField(blank=True, max_length=100)),
                ('url1', models.URLField(blank=True)),
                ('url2', models.URLField(blank=True)),
                ('url3', models.URLField(blank=True)),
                ('url4', models.URLField(blank=True)),
                ('url5', models.URLField(blank=True)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='laptops/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='laptops/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='laptops/')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='laptops/')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='laptops/')),
            ],
        ),
        migrations.RemoveField(
            model_name='offer',
            name='type',
        ),
        migrations.AddField(
            model_name='offer',
            name='product_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='product_module',
            field=models.CharField(choices=[('laptop', 'Laptop'), ('computer', 'Computer'), ('accessory', 'Accessory')], default='computer', max_length=20),
        ),
        migrations.CreateModel(
            name='AccessoryDynamicSpec',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=255)),
                ('value', models.TextField(blank=True)),
                ('accessory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dynamic_specs', to='myapp.accessory')),
            ],
            options={
                'unique_together': {('accessory', 'key')},
            },
        ),
        migrations.AddField(
            model_name='accessory',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accessories', to='myapp.accessorytype'),
        ),
        migrations.CreateModel(
            name='ComputerDynamicSpec',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=255)),
                ('value', models.TextField(blank=True)),
                ('computer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dynamic_specs', to='myapp.computer')),
            ],
            options={
                'unique_together': {('computer', 'key')},
            },
        ),
        migrations.AddField(
            model_name='computer',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='computers', to='myapp.computertype'),
        ),
        migrations.CreateModel(
            name='LaptopDynamicSpec',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=255)),
                ('value', models.TextField(blank=True)),
                ('laptop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dynamic_specs', to='myapp.laptop')),
            ],
            options={
                'unique_together': {('laptop', 'key')},
            },
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ProductType',
        ),
    ]
