# Generated by Django 5.0.6 on 2026-05-04 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_accessory_accessorytype_computer_computertype_laptop_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='description',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='name',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='oldprice',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='url1',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='url2',
        ),
    ]
